(function () {
  const softPngTheme = {
    id: "soft-png",
    label: "Soft PNG theme",
    labelKey: "theme.softPng",
    assets: {
      icons: {
        app: "./assets/icons/app-icon.png",
      },
      modes: {
        food: "./assets/modes/mode-food.png",
        drink: "./assets/modes/mode-drink.png",
        travel: "./assets/modes/mode-travel.png",
        number: "./assets/modes/mode-number.png",
        shopping: "./assets/modes/mode-shopping.png",
        gift: "./assets/modes/mode-gift.png",
        custom: "./assets/modes/mode-custom.png",
        world: "./assets/modes/mode-world.png",
      },
      empty: {
        favorites: "./assets/empty/empty-favorites.png",
        history: "./assets/empty/empty-history.png",
        notification: "./assets/empty/empty-notification.png",
        options: "./assets/empty/empty-options.png",
        world: "./assets/empty/empty-world.png",
      },
      gift: {
        box: "./assets/gift/gift-box.png",
        nameCard: "./assets/gift/name-card.png",
      },
      social: {
        defaultAvatar: "./assets/social/default-avatar.png",
        heartPopSprite: "./assets/social/heart-pop-sprite.png",
        uploadImage: "./assets/social/upload-image.png",
      },
      ui: {
        leafAccent: "./assets/ui/leaf-accent.png",
        notificationBell: "./assets/ui/notification-bell.png",
        wheelPointer: "./assets/ui/wheel-pointer.png",
        buttonIcons: {
          close: "./assets/ui/button-icons/close.png",
          edit: "./assets/ui/button-icons/edit.png",
          menu: "./assets/ui/button-icons/menu.png",
          copy: "./assets/ui/button-icons/copy.png",
          share: "./assets/ui/button-icons/share.png",
          trash: "./assets/ui/button-icons/trash.png",
          cancel: "./assets/ui/button-icons/cancel.png",
          confirm: "./assets/ui/button-icons/confirm.png",
          refresh: "./assets/ui/button-icons/refresh.png",
          shuffle: "./assets/ui/button-icons/shuffle.png",
          hide: "./assets/ui/button-icons/hide.png",
          tools: "./assets/ui/button-icons/tools.png",
        },
      },
    },
    cssVars: {
      "--asset-wheel-pointer": "url('./assets/ui/wheel-pointer.png')",
      "--asset-leaf-accent": "url('./assets/ui/leaf-accent.png')",
      "--asset-heart-pop-sprite": "url('./assets/social/heart-pop-sprite.png')",
      "--bg": "#fff8ef",
      "--bg-strong": "#fff1dd",
      "--bg-middle": "#fffdf8",
      "--surface": "rgba(255, 246, 231, 0.9)",
      "--surface-solid": "#fff5e6",
      "--surface-raised": "rgba(255, 249, 239, 0.96)",
      "--surface-control": "rgba(255, 241, 220, 0.86)",
      "--input-bg": "#fffdfa",
      "--glass": "rgba(255, 255, 255, 0.72)",
      "--ink": "#231b17",
      "--muted": "#85756a",
      "--soft": "#efe1d0",
      "--line": "rgba(80, 45, 24, 0.12)",
      "--accent": "#ff7a3d",
      "--accent-strong": "#eb5f24",
      "--mint": "#60c7a0",
      "--sun": "#ffd166",
      "--rose": "#ff9aa2",
      "--shadow": "0 24px 70px rgba(106, 57, 26, 0.16)",
      "--shadow-soft": "0 14px 35px rgba(106, 57, 26, 0.1)",
    },
  };

  const softPngDarkTheme = {
    id: "soft-png-dark",
    label: "Soft PNG dark theme",
    labelKey: "theme.softPngDark",
    assets: softPngTheme.assets,
    cssVars: {
      "--asset-wheel-pointer": "url('./assets/ui/wheel-pointer.png')",
      "--asset-leaf-accent": "url('./assets/ui/leaf-accent.png')",
      "--asset-heart-pop-sprite": "url('./assets/social/heart-pop-sprite.png')",
      "--bg": "#101722",
      "--bg-strong": "#172334",
      "--bg-middle": "#121d2c",
      "--surface": "rgba(25, 36, 51, 0.9)",
      "--surface-solid": "#1a2737",
      "--surface-raised": "rgba(33, 47, 65, 0.96)",
      "--surface-control": "rgba(39, 54, 74, 0.9)",
      "--input-bg": "#172333",
      "--glass": "rgba(31, 45, 62, 0.78)",
      "--ink": "#f7f8fb",
      "--muted": "#b8c4d2",
      "--soft": "#2d4056",
      "--line": "rgba(211, 224, 238, 0.16)",
      "--accent": "#ff9a6b",
      "--accent-strong": "#ff7542",
      "--mint": "#77d8b8",
      "--sun": "#f7cb62",
      "--rose": "#ff9ab1",
      "--shadow": "0 28px 76px rgba(0, 0, 0, 0.38)",
      "--shadow-soft": "0 16px 40px rgba(0, 0, 0, 0.26)",
    },
  };

  window.APP_DEFAULT_THEME_ID = "soft-png";
  window.APP_THEMES = Object.freeze({
    "soft-png": Object.freeze(softPngTheme),
    "soft-png-dark": Object.freeze(softPngDarkTheme),
  });
})();
