(function () {
  const softPngTheme = {
    id: "soft-png",
    label: "Soft PNG theme",
    labelKey: "theme.softPng",
    family: "soft-png",
    appearance: "light",
    descriptionKey: "theme.softPngDescription",
    assets: {
      icons: {
        app: "./assets/icons/app-icon.png",
      },
      modes: {
        food: "./assets/modes/mode-food.png",
        drink: "./assets/modes/mode-drink.png",
        travel: "./assets/modes/mode-travel.png",
        number: "./assets/modes/mode-number.png",
        shopping: "./assets/modes/mode-shopping.png",
        gift: "./assets/modes/mode-gift.png",
        custom: "./assets/modes/mode-custom.png",
        world: "./assets/modes/mode-world.png",
      },
      empty: {
        favorites: "./assets/empty/empty-favorites.png",
        history: "./assets/empty/empty-history.png",
        notification: "./assets/empty/empty-notification.png",
        options: "./assets/empty/empty-options.png",
        world: "./assets/empty/empty-world.png",
      },
      gift: {
        box: "./assets/gift/gift-box.png",
        nameCard: "./assets/gift/name-card.png",
      },
      social: {
        defaultAvatar: "./assets/social/default-avatar.png",
        heartPopSprite: "./assets/social/heart-pop-sprite.png",
        uploadImage: "./assets/social/upload-image.png",
      },
      ui: {
        leafAccent: "./assets/ui/leaf-accent.png",
        notificationBell: "./assets/ui/notification-bell.png",
        wheelPointer: "./assets/ui/wheel-pointer.png",
        buttonIcons: {
          close: "./assets/ui/button-icons/close.png",
          edit: "./assets/ui/button-icons/edit.png",
          menu: "./assets/ui/button-icons/menu.png",
          copy: "./assets/ui/button-icons/copy.png",
          share: "./assets/ui/button-icons/share.png",
          trash: "./assets/ui/button-icons/trash.png",
          cancel: "./assets/ui/button-icons/cancel.png",
          confirm: "./assets/ui/button-icons/confirm.png",
          refresh: "./assets/ui/button-icons/refresh.png",
          shuffle: "./assets/ui/button-icons/shuffle.png",
          hide: "./assets/ui/button-icons/hide.png",
          tools: "./assets/ui/button-icons/tools.png",
        },
      },
    },
    cssVars: {
      "--asset-wheel-pointer": "url('./assets/ui/wheel-pointer.png')",
      "--asset-leaf-accent": "url('./assets/ui/leaf-accent.png')",
      "--asset-heart-pop-sprite": "url('./assets/social/heart-pop-sprite.png')",
      "--theme-background-image": "none",
      "--theme-background-overlay": "linear-gradient(135deg, rgba(255, 248, 239, 0.1), rgba(255, 248, 239, 0.1))",
      "--bg": "#fff8ef",
      "--bg-strong": "#fff1dd",
      "--bg-middle": "#fffdf8",
      "--surface": "rgba(255, 246, 231, 0.9)",
      "--surface-solid": "#fff5e6",
      "--surface-raised": "rgba(255, 249, 239, 0.96)",
      "--surface-control": "rgba(255, 241, 220, 0.86)",
      "--input-bg": "#fffdfa",
      "--glass": "rgba(255, 255, 255, 0.72)",
      "--ink": "#231b17",
      "--muted": "#705f55",
      "--soft": "#efe1d0",
      "--line": "rgba(80, 45, 24, 0.12)",
      "--accent": "#ff7a3d",
      "--accent-strong": "#eb5f24",
      "--mint": "#60c7a0",
      "--sun": "#ffd166",
      "--rose": "#ff9aa2",
      "--shadow": "0 24px 70px rgba(106, 57, 26, 0.16)",
      "--shadow-soft": "0 14px 35px rgba(106, 57, 26, 0.1)",
    },
  };

  const softPngDarkTheme = {
    id: "soft-png-dark",
    label: "Soft PNG dark theme",
    labelKey: "theme.softPngDark",
    family: "soft-png",
    appearance: "dark",
    descriptionKey: "theme.softPngDarkDescription",
    assets: softPngTheme.assets,
    cssVars: {
      "--asset-wheel-pointer": "url('./assets/ui/wheel-pointer.png')",
      "--asset-leaf-accent": "url('./assets/ui/leaf-accent.png')",
      "--asset-heart-pop-sprite": "url('./assets/social/heart-pop-sprite.png')",
      "--theme-background-image": "none",
      "--theme-background-overlay": "linear-gradient(135deg, rgba(10, 18, 34, 0.12), rgba(10, 18, 34, 0.12))",
      "--bg": "#101722",
      "--bg-strong": "#172334",
      "--bg-middle": "#121d2c",
      "--surface": "rgba(25, 36, 51, 0.9)",
      "--surface-solid": "#1a2737",
      "--surface-raised": "rgba(33, 47, 65, 0.96)",
      "--surface-control": "rgba(39, 54, 74, 0.9)",
      "--input-bg": "#172333",
      "--glass": "rgba(31, 45, 62, 0.78)",
      "--ink": "#f7f8fb",
      "--muted": "#b8c4d2",
      "--soft": "#2d4056",
      "--line": "rgba(211, 224, 238, 0.16)",
      "--accent": "#ff9a6b",
      "--accent-strong": "#ff7542",
      "--mint": "#77d8b8",
      "--sun": "#f7cb62",
      "--rose": "#ff9ab1",
      "--shadow": "0 28px 76px rgba(0, 0, 0, 0.38)",
      "--shadow-soft": "0 16px 40px rgba(0, 0, 0, 0.26)",
    },
  };

  const auroraLightTheme = {
    id: "aurora-light",
    label: "Aurora light theme",
    labelKey: "theme.auroraLight",
    family: "aurora",
    appearance: "light",
    descriptionKey: "theme.auroraLightDescription",
    assets: softPngTheme.assets,
    cssVars: {
      "--asset-wheel-pointer": "url('./assets/ui/wheel-pointer.png')",
      "--asset-leaf-accent": "url('./assets/ui/leaf-accent.png')",
      "--asset-heart-pop-sprite": "url('./assets/social/heart-pop-sprite.png')",
      "--theme-background-image": "url('./assets/themes/aurora/aurora-light-background.png')",
      "--theme-background-overlay": "linear-gradient(135deg, rgba(244, 250, 255, 0.54), rgba(251, 245, 255, 0.44))",
      "--bg": "#eef5ff",
      "--bg-strong": "#e9e5ff",
      "--bg-middle": "#fbfdff",
      "--surface": "rgba(249, 252, 255, 0.92)",
      "--surface-solid": "#f9fcff",
      "--surface-raised": "rgba(255, 255, 255, 0.97)",
      "--surface-control": "rgba(237, 244, 255, 0.96)",
      "--input-bg": "#ffffff",
      "--glass": "rgba(252, 253, 255, 0.9)",
      "--ink": "#17213f",
      "--muted": "#53617f",
      "--soft": "#dce5fb",
      "--line": "rgba(68, 85, 136, 0.15)",
      "--accent": "#6677df",
      "--accent-strong": "#4d5dc2",
      "--mint": "#57c7bd",
      "--sun": "#f5c96d",
      "--rose": "#cf91ee",
      "--shadow": "0 24px 70px rgba(68, 84, 142, 0.18)",
      "--shadow-soft": "0 14px 35px rgba(68, 84, 142, 0.12)",
    },
  };

  const auroraDarkTheme = {
    id: "aurora-dark",
    label: "Aurora dark theme",
    labelKey: "theme.auroraDark",
    family: "aurora",
    appearance: "dark",
    descriptionKey: "theme.auroraDarkDescription",
    assets: softPngTheme.assets,
    cssVars: {
      "--asset-wheel-pointer": "url('./assets/ui/wheel-pointer.png')",
      "--asset-leaf-accent": "url('./assets/ui/leaf-accent.png')",
      "--asset-heart-pop-sprite": "url('./assets/social/heart-pop-sprite.png')",
      "--theme-background-image": "url('./assets/themes/aurora/aurora-dark-background.png')",
      "--theme-background-overlay": "linear-gradient(135deg, rgba(6, 12, 34, 0.5), rgba(10, 11, 42, 0.4))",
      "--bg": "#0b1029",
      "--bg-strong": "#101440",
      "--bg-middle": "#10183d",
      "--surface": "rgba(16, 26, 62, 0.92)",
      "--surface-solid": "#121b44",
      "--surface-raised": "rgba(20, 31, 70, 0.98)",
      "--surface-control": "rgba(33, 44, 89, 0.96)",
      "--input-bg": "#121c44",
      "--glass": "rgba(18, 28, 67, 0.9)",
      "--ink": "#f6f7ff",
      "--muted": "#ced6ee",
      "--soft": "#293966",
      "--line": "rgba(207, 219, 255, 0.17)",
      "--accent": "#9a88ff",
      "--accent-strong": "#7965e6",
      "--mint": "#66dfd2",
      "--sun": "#f7d782",
      "--rose": "#ef9ee9",
      "--shadow": "0 28px 78px rgba(0, 0, 0, 0.44)",
      "--shadow-soft": "0 16px 42px rgba(0, 0, 0, 0.3)",
    },
  };

  window.APP_DEFAULT_THEME_ID = "soft-png";
  window.APP_THEMES = Object.freeze({
    "soft-png": Object.freeze(softPngTheme),
    "soft-png-dark": Object.freeze(softPngDarkTheme),
    "aurora-light": Object.freeze(auroraLightTheme),
    "aurora-dark": Object.freeze(auroraDarkTheme),
  });
})();
